Add com.jfrog.includeAllBuildFile flag
jfrog/gradle-dep-tree pull request #9
Opened 2023-03-19 14:48 UTC by omerzi

- [ ] All [tests](../CONTRIBUTING.md#tests) passed. If this feature is not already covered by the tests, I added new
  tests.

-----

2023-03-19 14:55 UTC, yahavi requested changes

2023-03-19 14:55 UTC, yahavi commented on README.md
> +contain a build.gradle file. To generate a dependency tree for each project that contains a build file, set the `-Dcom.jfrog.includeAllBuildFile` flag to `true`.
```suggestion
contain a build.gradle file. To generate a dependency tree for each subproject that contains a Gradle build file, set the `-Dcom.jfrog.includeAllBuildFile` flag to `true`.
```

2023-03-19 14:55 UTC, yahavi commented on src/main/java/com/jfrog/tasks/GenerateDepTrees.java
> -        for (Project project : (Set<Project>) getProject().getSubprojects()) {
I'm not sure this will work on Java 8

2023-03-19 15:14 UTC, omerzi commented on README.md
> +contain a build.gradle file. To generate a dependency tree for each project that contains a build file, set the `-Dcom.jfrog.includeAllBuildFile` flag to `true`.
done

2023-03-19 15:15 UTC, omerzi commented on src/main/java/com/jfrog/tasks/GenerateDepTrees.java
> -        for (Project project : (Set<Project>) getProject().getSubprojects()) {
done

2023-03-20 10:46 UTC, yahavi requested changes

2023-03-20 10:46 UTC, yahavi commented on src/functionalTest/java/com/jfrog/tasks/IncludeAllBuildFilesTest.java
> + * @author yahavi
Please update the description

2023-03-20 13:38 UTC, merged